### ISSUE TITLE
AppRater as new Label of my App

### ISSUE THREAD

**Issue by afaucogney** [codechimp-org/AppRater#46]
I'm just starting using AppRater for what it is intended to do, and after a couple of hours of dev (out of scope of AppRater), my app name (launcher name + actionbartitle) became "AppRater", even if in my manifest it my normal name. Any idea ?

**Comment by andrew-codechimp** [comment]
Are you using the latest version of AppRater?
There was an issue with this very early on.

**Comment by afaucogney** [comment]
Yes I saw on the old issues.
I just use the gradle as writen in the project page.
    compile 'com.github.codechimp-org.apprater:library:1.0.+'

**Comment by afaucogney** [comment]
I fixed the version to the 1.0.27 and it soved the issue. What the hell is doing Gradle....
