### ISSUE TITLE
incorrect localization folder name for HK & TW

### ISSUE THREAD

**Issue by innopage** [codechimp-org/AppRater#49]
I'm a Chinese developer in Hong Kong,  for HK & TW, we use Traditional Chinese, however, when using your library, it is displaying Simplified Chines.  Upon closer inspection, it appears you are using the wrong folder name

values-zh-HK    should be values-zh-rHK
values-zh-TW   should be values-zh-rTW

Please kindly fix at your convenience

**Comment by andrew-codechimp** [comment]
Thanks for spotting this.  Now fixed and pushed to Maven central
