### ISSUE TITLE
Vietnamese Translation

### ISSUE THREAD

**Issue by thangnguyendt** [codechimp-org/AppRater#58]
Hi,

the vietnamese translation is pretty clumsy. I created this issue to contribute the right translation

Rate MyApp -> Bình Chọn MyApp

If you enjoy using this app, please take a moment to rate it. Thanks for your support!
"the translation for the message in vietnamese is ok"

Later -> Để Sau
No Thanks -> Không, Cảm Ơn
Rate now -> Bình Chọn

**Comment by andrew-codechimp** [comment]
Manually added into translations branch, will be pushed to master & Maven in a few days, thanks for the contribution.
