### ISSUE TITLE
Hebrew language does not display

### ISSUE THREAD

**Issue by danieltskv** [codechimp-org/AppRater#68]
As Hebrew can be localized as `he` and `iw`, the AppRater library only includes a `values-he` folder, which does not display Hebrew on some devices. I tested on a Nexus 5 localized to Hebrew, and it shows English text. 

When adding a `values-iw` folder with the same content as `values-he`, it displays Hebrew.
Can we have a fix which includes the `values-iw` folder?
Thank you.

**Comment by andrew-codechimp** [comment]
Seems a common issue, I'll duplicate this folder and release soon.
[http://stackoverflow.com/questions/8393771/android-not-using-finding-my-hebrew-localization](http://stackoverflow.com/questions/8393771/android-not-using-finding-my-hebrew-localization)

**Comment by andrew-codechimp** [comment]
Now completed and pushed to Maven Central
