### ISSUE TITLE
Where to find the AppRate's files to edit

### ISSUE THREAD

**Issue by ihpalash** [codechimp-org/AppRater#69]
Hey Andrew I pulled the apprate plugin and integrated with my android app . But I want to edit some stuff. I looked through the whole project, and found nothing related to apprate plugin. 

PS: I pulled using gradle. Can you tell me where to find the files?

**Comment by andrew-codechimp** [comment]
Gradle doesn't pull the source, just a lib.

If you want to modify you'll have to download the code, add it manually as a module into your project and remove the gradle reference.
