### ISSUE TITLE
app_name in strings.xml overridden by AppRater

### ISSUE THREAD

**Issue by AngeloAvv** [codechimp-org/AppRater#70]
I suggest you to change this label name, since the application's name will change in AppRate due to overriding. Someone who will keep this string label the same as is done during the project creation will face this issue.

**Comment by andrew-codechimp** [comment]
There isn't a label of app_name in latest strings.xml, there was many versions ago so ensure you're using the latest library version.

**Comment by AngeloAvv** [comment]
I'm using: compile 'com.github.codechimp-org.apprater:library:1.0.4'

**Comment by andrew-codechimp** [comment]
Current version is 1.0.34 so try updating.
